version: '3.9'

services:

  web_nginx:
    container_name: "web_nginx"
    image: nginx:alpine
    depends_on:
      - fast_api
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - custom

  fast_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "fast_api_shop"
    volumes:
      - .:/online_shop
    env_file:
      - .env
    depends_on:
      - database
      - database_test
      - redis_app
      - redis_app_test
    networks:
      - custom

  database:
    image: postgres:latest
    restart: always
    container_name: "database_online_shop"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5454:5432"
    networks:
      - custom

  database_test:
    image: postgres:latest
    restart: always
    container_name: "database_online_shop_test"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shop_db_test
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5452:5432"
    networks:
      - custom

  redis_app:
    image: redis:latest
    restart: always
    env_file:
      - .env
    container_name: "redis_online_shop"
    ports:
      - "6000:6379"
    networks:
      - custom

  redis_app_test:
    image: redis:latest
    restart: always
    env_file:
      - .env
    container_name: "redis_online_shop_test"
    ports:
      - "6001:6379"
    networks:
      - custom

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "celery_shop"
    depends_on:
      - redis_app
      - redis_app_test
      - database
      - database_test
    volumes:
      - ./:/app
      - .env:/app/.env:ro
    env_file:
      - .env
    networks:
      - custom

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "flower_shop"
    depends_on:
      - worker
    ports:
      - "5555:5555"
    networks:
      - custom

  prometheus_shop:
    image: prom/prometheus
    container_name: "prometheus_shop"
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      - fast_api
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - custom

  grafana_shop:
    image: grafana/grafana
    container_name: "grafana_shop"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
    depends_on:
      - prometheus_shop
    networks:
      - custom

networks:
  custom:
    driver: bridge

volumes:
  grafana-data:
  grafana-config:
  prometheus-data:





