version: '3.9'

services:

  fast_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "fast_api_shop"
    volumes:
      - .:/online_shop
    env_file:
      - .env
    depends_on:
      - database
      - database_test
      - redis_app
    ports:
      - "8000:8000"
    networks:
      - custom

  database:
    image: postgres
    restart: always
    container_name: "database_online_shop"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5454:5432"
    networks:
      - custom

  database_test:
    image: postgres
    restart: always
    container_name: "database_online_shop_test"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shop_db_test
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5452:5432"
    networks:
      - custom

  redis_app:
    image: redis
    restart: always
    env_file:
      - .env
    container_name: "redis_online_shop"
    ports:
      - "6000:6379"
    networks:
      - custom

networks:
  custom:
    driver: bridge

