version: '3.9'

services:

  database:
    image: postgres
    restart: always
    container_name: "database_online_shop"
    volumes:
      - /home/nikita/PSQL/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5454:5432"
    networks:
      - custom

  database_test:
    image: postgres
    restart: always
    container_name: "database_online_shop_test"
    volumes:
      - /home/nikita/PSQL/data_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shop_db_test
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5452:5432"
    networks:
      - custom

  redis_app:
    image: redis
    restart: always
    env_file:
      - .env
    container_name: "redis_online_shop"
    ports:
      - "6000:6379"
    networks:
      - custom

networks:
  custom:
    driver: bridge

