"""Create table v7

Revision ID: d4b8bfd1764d
Revises: a625298f9a77
Create Date: 2024-01-10 13:13:50.646060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4b8bfd1764d"
down_revision: Union[str, None] = "a625298f9a77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("name_image", sa.String(), nullable=False))
    op.create_unique_constraint(None, "products", ["name_image"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    op.drop_column("products", "name_image")
    # ### end Alembic commands ###
