"""Add column reserved_quantity in table product

Revision ID: 3ed1a0b53418
Revises: 0999cc4b2ee4
Create Date: 2024-02-24 13:34:17.546510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed1a0b53418'
down_revision: Union[str, None] = '0999cc4b2ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('reserved_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'reserved_quantity')
    # ### end Alembic commands ###
