"""Create table v5

Revision ID: a625298f9a77
Revises: e20defe2a846
Create Date: 2024-01-05 20:14:57.298754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a625298f9a77"
down_revision: Union[str, None] = "e20defe2a846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "orders", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="unique")
    # ### end Alembic commands ###
