"""Update name tables

Revision ID: 2e3a5e9de9e2
Revises: 78c83f56ee53
Create Date: 2024-02-06 22:14:57.266914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e3a5e9de9e2"
down_revision: Union[str, None] = "78c83f56ee53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
