"""Add column reserved_quantity in table product v2

Revision ID: 657d3718f12f
Revises: 3ed1a0b53418
Create Date: 2024-02-24 13:36:35.887593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657d3718f12f'
down_revision: Union[str, None] = '3ed1a0b53418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'reserved_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'reserved_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
