"""Add column discount in product

Revision ID: 0999cc4b2ee4
Revises: f7b695b040f1
Create Date: 2024-02-22 17:44:50.785290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0999cc4b2ee4'
down_revision: Union[str, None] = 'f7b695b040f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Float(), nullable=False, comment='Скидка передаётся в процентах'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
